---
- name: "Baikor_R package registry: Resolve credentials"
  ansible.builtin.set_fact:
    baikor_package_registry_username: >-
      {{ inv_addons.baikor_r.package_registry.username
         | default(lookup('env', 'BAIKOR_R_PACKAGE_REGISTRY_USERNAME'), true) }}
    baikor_package_registry_password: >-
      {{ inv_addons.baikor_r.package_registry.password
         | default(lookup('env', 'BAIKOR_R_PACKAGE_REGISTRY_PASSWORD'), true) }}
  no_log: true
